# This file contains the default values for the aiSSEMBLE Spark Infrastructure Helm chart.

aissemble-spark-history-chart:
  app:
    name: "spark-history"
  eventVolume:
    enabled: true

aissemble-hive-metastore-service-chart:
  mysql:
    auth:
      # Note: Changing these values requires removal of the `hive-metastore-db-0` PVC, or manual modification of the
      # persisted database.
      username: hive
      # NB: UCS
      rootPassword: hive
      replicationPassword: hive
      password: hive

  deployment:
    env:
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: remote-auth-config
            key: AWS_SECRET_ACCESS_KEY
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: remote-auth-config
            key: AWS_ACCESS_KEY_ID

  configMap:
    metastoreServiceConfig:
      properties:
        - name: javax.jdo.option.ConnectionUserName
          value: hive
          description: Username to use against metastore database
          # NB: UCS
        - name: javax.jdo.option.ConnectionPassword
          value: hive
          description: Password to use against metastore database
        - name: metastore.warehouse.dir
          value: s3a://spark-infrastructure/warehouse
        - name: fs.s3a.endpoint
          value: http://s3-local:4566
        - name: fs.s3a.path.style.access
          value: true
